# Generated by Django 4.1.1 on 2022-10-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparación',
            new_name='preparacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='descripcion',
        ),
    ]
