# Generated by Django 4.1.1 on 2022-10-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_remove_receta_foto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparación',
            new_name='preparacion',
        ),
    ]
