# Generated by Django 4.1.1 on 2022-10-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_rename_preparación_receta_preparacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparacion',
            new_name='preparación',
        ),
    ]
