# Generated by Django 4.1.1 on 2022-10-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_rename_preparacion_receta_preparación'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=500),
            preserve_default=False,
        ),
    ]
