# Generated by Django 4.1.1 on 2022-10-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_rename_preparación_receta_preparacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto',
            field=models.FileField(upload_to='recetas'),
        ),
    ]
