POST http://localhost:5000/api2/recipes
Content-Type: application/json

{
  "name": "Glass of Water",
  "instructions": [
    "Grab a Jar of water.",
    "Serve in a glass."
  ],
  "ingredients": [
    {
      "name": "Water",
      "quantity": {
        "quantity": "1",
        "unit": "Jar"
      }
    }
  ],
  "slug": "water-glass"
}
